# Generated by Django 2.2.5 on 2019-10-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='hashtags', to='articles.Article'),
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='content',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='content',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
