# Generated by Django 2.2.5 on 2019-10-23 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
